In [2]:
import pandas as pd

pair_df = pd.read_csv ('semeval-2022_task8_train-data_batch.csv')
pair_df

,url1_lang,url2_lang,pair_id,link1,link2,ia_link1,ia_link2,Geography,Entities,Time,Narrative,Overall,Style,Tone
0,en,en,1484084337_1484110209,https://www.washingtonpost.com/local/virginia-...,https://www.washingtonpost.com/world/the_ameri...,https://web.archive.org/web/www.washingtonpost...,https://web.archive.org/web/www.washingtonpost...,4.0,4.000000,1.000000,4.000000,4.000000,1.666667,2.000000
1,en,en,1484396422_1483924666,https://www.stlucianewsonline.com/guyana-three...,https://www.thestar.com/news/world/europe/2020...,https://web.archive.org/web/www.stlucianewsonl...,https://web.archive.org/web/www.thestar.com/ne...,4.0,4.000000,1.000000,4.000000,3.666667,1.666667,1.333333
2,en,en,1484698254_1483758694,https://www.teaparty.org/trump-brings-in-2020-...,https://www.timesofisrael.com/trump-says-he-do...,https://web.archive.org/web/www.teaparty.org/t...,https://web.archive.org/web/www.timesofisrael....,1.0,2.000000,1.000000,2.333333,2.333333,1.000000,1.333333
3,en,en,1576314516_1576455088,https://gadgets.ndtv.com/apps/news/zomato-uber...,https://gadgets.ndtv.com/internet/news/indian-...,https://web.archive.org/web/gadgets.ndtv.com/a...,https://web.archive.org/web/gadgets.ndtv.com/i...,1.0,2.333333,2.666667,1.666667,2.000000,1.666667,1.666667
4,en,en,1484036253_1483894099,https://news.yahoo.com/india-approves-third-mo...,https://www.channelnewsasia.com/news/asia/indi...,https://web.archive.org/web/news.yahoo.com/ind...,https://web.archive.org/web/www.channelnewsasi...,1.0,1.250000,1.000000,1.250000,1.250000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2934,ar,ar,1612662952_1575561189,https://cedarnews.net/diverts/235258/,http://www.ahewar.org/news/s.news.asp?nid=3845923,https://web.archive.org/web/cedarnews.net/dive...,https://web.archive.org/web/www.ahewar.org/new...,3.0,3.000000,3.000000,3.000000,3.000000,1.000000,1.000000
2935,ar,ar,1610474240_1502834406,https://www.yemenakhbar.com/2411537,https://alsahwa-yemen.net/p-37479,https://web.archive.org/web/www.yemenakhbar.co...,https://web.archive.org/web/alsahwa-yemen.net/...,1.0,1.000000,4.000000,2.000000,2.000000,1.000000,1.000000
2936,ar,ar,1548303752_1548337846,https://elbashayer.com/2505935/2020/03/14/%d8%...,http://www.light-dark.net/t1630170--الأرصاد-ال...,https://web.archive.org/web/elbashayer.com/250...,https://web.archive.org/web/www.light-dark.net...,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2937,ar,ar,1575309020_1569847683,https://www.alquds.co.uk/ابنة-رجل-أعمال-سعودي-...,http://www.ahewar.org/news/s.news.asp?nid=3836387,https://web.archive.org/web/www.alquds.co.uk/ا...,https://web.archive.org/web/www.ahewar.org/new...,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2938,ar,ar,1568535170_1558667669,https://www.alarabiya.net/ar/aswaq/oil-and-gas...,https://www.khaberni.com/news/339402,https://web.archive.org/web/www.alarabiya.net/...,https://web.archive.org/web/www.khaberni.com/n...,3.0,2.000000,2.000000,2.000000,3.000000,1.000000,1.000000

In [14]:
path = '1_training_csv/all_training_with_translated_title.csv'
train_df = pd.read_csv(path)
train_df

,id,title,meta_lang,translated_lang,translated_title,keywords,meta_keywords,tags,publish_date,text
0,1484067970,Valle de México recibe 2020 con mala calidad d...,NaN,es,Valley of Mexico receives 2020 with poor air q...,[],"['calidad de aire', 'cdmx', 'contaminación', '...",[],Wed Jan 1 10:36:30 2020,Milenio Digital\n\nEl Sistema de Monitoreo Atm...
1,1536953314,MinInterior lideró en Cali Comisión de Segurid...,NaN,es,Mininterior led in Cali Security Commission: w...,[],"['mininterior', 'cali', 'Comisión Nacional de ...",['Leer más sobre ¡Asombroso! Mira lo que suced...,NaN,"""La comunidad en Cali y en Colombia deben tene..."
2,1547327916,El Speedagro Rally Argentina 2020 ha sido apla...,es,es,The Speedagro Rally Argentina 2020 has been po...,[],[''],[],NaN,C omo resultado de los acontecimientos mundial...
3,1484261908,Trump’s lawyer Giuliani says he’s willing to t...,en,en,Trump’s lawyer Giuliani says he’s willing to t...,[],"[""Azerbaijan's news"", ""Georgia's news"", ""Kazak...","['USA', 'Donald Trump', 'impeachment']",Thu Jan 2 04:44:00 2020,"Rudy Giuliani, personal attorney to US Preside..."
4,1484076690,Reprime EU a manifestantes con gases lacrimóge...,es,es,Represses EU to demonstrators with tear gas in...,[],[''],"['Irak', 'embajada', 'gases lacrimógenos']",Wed Jan 1 16:53:46 2020,Afp\n\nBagdad. Las fuerzas de seguridad de la ...
...,...,...,...,...,...,...,...,...,...,...
5540,1484101809,"AAP slams Congress, previous SAD-BJP alliance ...",en,en,"AAP slams Congress, previous SAD-BJP alliance ...",[],[''],[],NaN,"Chandigarh (Punjab) [India], Jan 1 (ANI): The ..."
5541,1484040153,Start the Year on a Positive Note With These S...,en,en,Start the Year on a Positive Note With These S...,[],[''],"['Healthy Living', 'Self-Care', 'Books', 'Netf...",Wed Jan 1 07:30:13 2020,"Without fail, Netflix has become my winding do..."
5542,1484188201,Everything new to Netflix in January and what ...,NaN,en,Everything new to Netflix in January and what ...,[],['Netflix'],[],Wed Jan 1 10:42:52 2020,Sign up to FREE daily email alerts from liverp...
5543,1484125412,Zagłada ptaków w Polsce. W środę zabijały je w...,NaN,pl,"Hollow birds in Poland.On Wednesday, the explo...",[],[''],[],Wed Jan 1 19:56:23 2020,Sylwestrowe pokazy sztucznych ogni doprowadził...
5544,1484205799,"As Brexit Pulls Britain Apart, It Could Bring ...",en,en,"As Brexit Pulls Britain Apart, It Could Bring ...",[],[''],"['Ireland', 'Northern Ireland', 'Brexit']",Fri Nov 29 00:00:00 2019,"As Brexit Pulls Britain Apart, It Could Bring ..."

In [19]:
d = train_df.set_index('id').to_dict()

In [32]:
type(list(d['title'].keys())[0])

int

In [42]:
train_dict = {}
for index, row in train_df.iterrows():
    row['id'] = str(row['id'])
    train_dict[row['id']] = {"title":row["title"],"meta_lang":row["meta_lang"],"translated_lang":row["translated_lang"],
                             "translated_title":row["translated_title"]
                             }

In [44]:
train_dict['1484067970']

{'title': 'Valle de México recibe 2020 con mala calidad del aire',
 'meta_lang': nan,
 'translated_lang': 'es',
 'translated_title': 'Valley of Mexico receives 2020 with poor air quality'}

In [62]:
# Geography, Entities, Time,Narrative,Overall,Style,Tone
import numpy as np

pair_df['title1'] = pair_df['title1'].astype(str)
pair_df['title2'] = pair_df['title2'].astype(str)
for i, row in pair_df.iterrows():
    ids = row['pair_id'].split('_')

    pair_df.at[i,'id1'] = str(ids[0])
    pair_df.at[i,'id2'] = str(ids[1])
    
    if str(ids[0]) in train_dict.keys():
        pair_df.at[i,'title1'] = train_dict[ids[0]]['translated_title']
    else: 
        pair_df.at[i,'title1'] = np.nan
        
    if str(ids[1]) in train_dict.keys():
        pair_df.at[i,'title2'] = train_dict[ids[1]]['translated_title']
    else: 
        pair_df.at[i,'title2'] = np.nan

In [63]:
pair_df

,url1_lang,url2_lang,pair_id,link1,link2,ia_link1,ia_link2,Geography,Entities,Time,Narrative,Overall,Style,Tone,id1,id2,title1,title2
0,en,en,1484084337_1484110209,https://www.washingtonpost.com/local/virginia-...,https://www.washingtonpost.com/world/the_ameri...,https://web.archive.org/web/www.washingtonpost...,https://web.archive.org/web/www.washingtonpost...,4.0,4.000000,1.000000,4.000000,4.000000,1.666667,2.000000,1484084337,1484110209,Virginia man arrested in fatal DUI crash in We...,Haiti’s leader marks independence day amid sec...
1,en,en,1484396422_1483924666,https://www.stlucianewsonline.com/guyana-three...,https://www.thestar.com/news/world/europe/2020...,https://web.archive.org/web/www.stlucianewsonl...,https://web.archive.org/web/www.thestar.com/ne...,4.0,4.000000,1.000000,4.000000,3.666667,1.666667,1.333333,1484396422,1483924666,Guyana: Three injured after car crashes into u...,Fire kills more than 30 animals at zoo in west...
2,en,en,1484698254_1483758694,https://www.teaparty.org/trump-brings-in-2020-...,https://www.timesofisrael.com/trump-says-he-do...,https://web.archive.org/web/www.teaparty.org/t...,https://web.archive.org/web/www.timesofisrael....,1.0,2.000000,1.000000,2.333333,2.333333,1.000000,1.333333,1484698254,1483758694,Trump Brings In 2020 At Mar-a-Lago: ‘We’re Goi...,"Trump says he does not expect war with Iran, ‘..."
3,en,en,1576314516_1576455088,https://gadgets.ndtv.com/apps/news/zomato-uber...,https://gadgets.ndtv.com/internet/news/indian-...,https://web.archive.org/web/gadgets.ndtv.com/a...,https://web.archive.org/web/gadgets.ndtv.com/i...,1.0,2.333333,2.666667,1.666667,2.000000,1.666667,1.666667,1576314516,1576455088,Zomato Buys Uber's Food Delivery Business in I...,Indian Online Food Delivery Market to Hit $8 B...
4,en,en,1484036253_1483894099,https://news.yahoo.com/india-approves-third-mo...,https://www.channelnewsasia.com/news/asia/indi...,https://web.archive.org/web/news.yahoo.com/ind...,https://web.archive.org/web/www.channelnewsasi...,1.0,1.250000,1.000000,1.250000,1.250000,1.000000,1.000000,1484036253,1483894099,"India approves third moon mission, months afte...",India targets new moon mission in 2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2934,ar,ar,1612662952_1575561189,https://cedarnews.net/diverts/235258/,http://www.ahewar.org/news/s.news.asp?nid=3845923,https://web.archive.org/web/cedarnews.net/dive...,https://web.archive.org/web/www.ahewar.org/new...,3.0,3.000000,3.000000,3.000000,3.000000,1.000000,1.000000,1612662952,1575561189,The full story of the suffering of a family of...,Dialogue
2935,ar,ar,1610474240_1502834406,https://www.yemenakhbar.com/2411537,https://alsahwa-yemen.net/p-37479,https://web.archive.org/web/www.yemenakhbar.co...,https://web.archive.org/web/alsahwa-yemen.net/...,1.0,1.000000,4.000000,2.000000,2.000000,1.000000,1.000000,1610474240,1502834406,A violent explosions in the capital of Sana'a,15 Houthi killed in the honor of East Sanaa
2936,ar,ar,1548303752_1548337846,https://elbashayer.com/2505935/2020/03/14/%d8%...,http://www.light-dark.net/t1630170--الأرصاد-ال...,https://web.archive.org/web/elbashayer.com/250...,https://web.archive.org/web/www.light-dark.net...,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1548303752,1548337846,Meteorology Unveils weather conditions until t...,Meteorology surprised Egyptians .. Wait for se...
2937,ar,ar,1575309020_1569847683,https://www.alquds.co.uk/ابنة-رجل-أعمال-سعودي-...,http://www.ahewar.org/news/s.news.asp?nid=3836387,https://web.archive.org/web/www.alquds.co.uk/ا...,https://web.archive.org/web/www.ahewar.org/new...,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1575309020,1569847683,The daughter of a great Saudi businessman rais...,Dialogue
2938,ar,ar,1568535170_1558667669,https://www.alarabiya.net/ar/aswaq/oil-and-gas...,https://www.khaberni.com/news/339402,https://web.archive.org/web/www.alarabiya.net/...,https://web.archive.org/web/www.khaberni.com/n...,3.0,2.000000,2.000000,2.000000,3.000000,1.000000,1.000000,1568535170,1558667669,Tramp meets the heads of oil companies .. What...,Brent crude barrel of $ 26.27

In [66]:
path = '1_training_csv/translated_title_pair.csv'
pair_df.to_csv(path,index=False)